/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

/**
 *
 * @author mailon2
 */
public class OperacionesAlgebraRelacional extends javax.swing.JFrame {
    
    /**
     * Creates new form OperacionesAlgebraRelacional
     */
    public OperacionesAlgebraRelacional() {
        initComponents();
    
        this.setTitle("Menu de operaciones de álgebra relacional");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSeleccion = new javax.swing.JButton();
        jButtonProyeccion = new javax.swing.JButton();
        jButtonUnion = new javax.swing.JButton();
        jButtonDiferenciaConjuntos = new javax.swing.JButton();
        jButtonProductoCartesiano = new javax.swing.JButton();
        jButtonIntersecion = new javax.swing.JButton();
        jButtonDivision = new javax.swing.JButton();
        jButtonRenombrar = new javax.swing.JButton();
        jButtonConcatenacion = new javax.swing.JButton();
        jButtonConcaNatural = new javax.swing.JButton();
        jButtonAgregación = new javax.swing.JButton();
        jButtonAgrupación = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSeleccion.setText("Selección");
        jButtonSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionActionPerformed(evt);
            }
        });

        jButtonProyeccion.setText("Proyección");
        jButtonProyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProyeccionActionPerformed(evt);
            }
        });

        jButtonUnion.setText("Unión");
        jButtonUnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnionActionPerformed(evt);
            }
        });

        jButtonDiferenciaConjuntos.setText("Diferecia de conjuntos");
        jButtonDiferenciaConjuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiferenciaConjuntosActionPerformed(evt);
            }
        });

        jButtonProductoCartesiano.setText("Producto Cartesiano");
        jButtonProductoCartesiano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductoCartesianoActionPerformed(evt);
            }
        });

        jButtonIntersecion.setText("Intersección");
        jButtonIntersecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIntersecionActionPerformed(evt);
            }
        });

        jButtonDivision.setText("División");
        jButtonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisionActionPerformed(evt);
            }
        });

        jButtonRenombrar.setText("Renombrar");
        jButtonRenombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenombrarActionPerformed(evt);
            }
        });

        jButtonConcatenacion.setText("Concatenación");
        jButtonConcatenacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcatenacionActionPerformed(evt);
            }
        });

        jButtonConcaNatural.setText("Concatenación Natural");
        jButtonConcaNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcaNaturalActionPerformed(evt);
            }
        });

        jButtonAgregación.setText("Agregación");
        jButtonAgregación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregaciónActionPerformed(evt);
            }
        });

        jButtonAgrupación.setText("Agrupación");
        jButtonAgrupación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgrupaciónActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jButtonAtras)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonProyeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUnion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jButtonSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDiferenciaConjuntos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonProductoCartesiano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonIntersecion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonConcatenacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonConcaNatural, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jButtonAgregación, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAgrupación, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRenombrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSeleccion)
                    .addComponent(jButtonDivision))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProyeccion)
                    .addComponent(jButtonRenombrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUnion)
                    .addComponent(jButtonConcatenacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDiferenciaConjuntos)
                    .addComponent(jButtonConcaNatural))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProductoCartesiano)
                    .addComponent(jButtonAgregación))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIntersecion)
                    .addComponent(jButtonAgrupación))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonAtras))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregaciónActionPerformed
        // TODO add your handling code here:
        VentanaAgregacion ventanaAgregacion = new VentanaAgregacion(this);
        ventanaAgregacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAgregaciónActionPerformed

    private void jButtonSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionActionPerformed
        VentanaSeleccion ventanaSeleccion = new VentanaSeleccion(this);
        ventanaSeleccion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSeleccionActionPerformed

    private void jButtonUnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnionActionPerformed
        // TODO add your handling code here:
        VentanaUnion ventanaUnion = new VentanaUnion(this);
        ventanaUnion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonUnionActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonRenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenombrarActionPerformed
        // TODO add your handling code here:
        VentanaRenombrarAtributos ventanaRenombrar = new VentanaRenombrarAtributos(this);
        ventanaRenombrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRenombrarActionPerformed

    private void jButtonDiferenciaConjuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiferenciaConjuntosActionPerformed
        // TODO add your handling code here:
        VentanaDiferenciaConjuntos ventanaDiferenciaConjuntos = new VentanaDiferenciaConjuntos(this);
        ventanaDiferenciaConjuntos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDiferenciaConjuntosActionPerformed

    private void jButtonConcatenacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcatenacionActionPerformed
        // TODO add your handling code here:
        VentanaConcatenacion ventanaConcatenacion = new VentanaConcatenacion(this);
        ventanaConcatenacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonConcatenacionActionPerformed

    private void jButtonProyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProyeccionActionPerformed
        // TODO add your handling code here:
        VentanaProyeccion ventanaProc = new VentanaProyeccion(this);
        ventanaProc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonProyeccionActionPerformed

    private void jButtonProductoCartesianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductoCartesianoActionPerformed
        // TODO add your handling code here:
        VentanaProductoCartesiano ventana = new VentanaProductoCartesiano(this);
        this.setVisible(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonProductoCartesianoActionPerformed

    private void jButtonIntersecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIntersecionActionPerformed
        // TODO add your handling code here:
        VentanaInterseccion ventana = new VentanaInterseccion(this);
        this.setVisible(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonIntersecionActionPerformed

    private void jButtonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisionActionPerformed
        // TODO add your handling code here:
        VentanaDivision ventana = new VentanaDivision(this);
        this.setVisible(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonDivisionActionPerformed

    private void jButtonConcaNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcaNaturalActionPerformed
        // TODO add your handling code here:
        VentanaNaturalJoin ventana = new VentanaNaturalJoin(this);
        this.setVisible(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonConcaNaturalActionPerformed

    private void jButtonAgrupaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgrupaciónActionPerformed
        // TODO add your handling code here:
        VentanaAgrupacion ventana = new VentanaAgrupacion(this);
        this.setVisible(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonAgrupaciónActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        MenuFunciones ventana = new MenuFunciones();
        this.setVisible(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacionesAlgebraRelacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacionesAlgebraRelacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacionesAlgebraRelacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacionesAlgebraRelacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperacionesAlgebraRelacional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregación;
    private javax.swing.JButton jButtonAgrupación;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonConcaNatural;
    private javax.swing.JButton jButtonConcatenacion;
    private javax.swing.JButton jButtonDiferenciaConjuntos;
    private javax.swing.JButton jButtonDivision;
    private javax.swing.JButton jButtonIntersecion;
    private javax.swing.JButton jButtonProductoCartesiano;
    private javax.swing.JButton jButtonProyeccion;
    private javax.swing.JButton jButtonRenombrar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSeleccion;
    private javax.swing.JButton jButtonUnion;
    // End of variables declaration//GEN-END:variables
}
