/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyectobd1.Singleton;
import proyectobd1.Tabla;

/**
 *
 * @author mailon2
 */
public class VentanaProyeccion extends javax.swing.JFrame {
    
    OperacionesAlgebraRelacional ventanaMain;
    /**
     * Creates new form VentanaProyeccion
     */
    public VentanaProyeccion() {
        initComponents();
    }
    public VentanaProyeccion(OperacionesAlgebraRelacional ventana){
        initComponents();
        this.ventanaMain = ventana;
        this.setTitle("Realización de proyección");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTabla = new javax.swing.JTextField();
        jTextFieldResult = new javax.swing.JTextField();
        jTextFieldExpr = new javax.swing.JTextField();
        jButtonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProyec = new javax.swing.JTable();
        jButtonEjec = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSql = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaAlg = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre Tabla:");

        jLabel2.setText("Expresión:");

        jLabel3.setText("Tabla Resultante:");

        jButtonSalir.setText("Atras");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jTableProyec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableProyec);

        jButtonEjec.setText("Ejecutar");
        jButtonEjec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjecActionPerformed(evt);
            }
        });

        jTextAreaSql.setColumns(20);
        jTextAreaSql.setRows(5);
        jScrollPane2.setViewportView(jTextAreaSql);

        jTextAreaAlg.setColumns(20);
        jTextAreaAlg.setRows(5);
        jScrollPane3.setViewportView(jTextAreaAlg);

        jLabel4.setText("Equivalente en SQL:");

        jLabel5.setText("Equivalente en Álgebra Relacional:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldResult))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldTabla)
                                        .addComponent(jTextFieldExpr, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonSalir)
                                .addGap(57, 57, 57)
                                .addComponent(jButtonEjec)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(10, 10, 10))
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSalir)
                            .addComponent(jButtonEjec))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldExpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.ventanaMain.setVisible(true);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonEjecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjecActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldResult.getText().isEmpty()){
            if(Singleton.getInstance().getConexionServidor().existeTablaP(jTextFieldTabla.getText())){
                if((Singleton.getInstance().getConexionServidor().existeTablaP(jTextFieldResult.getText()) != true) && 
                        (Singleton.getInstance().getConexionServidor().esTablaTemporalP(jTextFieldResult.getText()) != true)){
                    if(Singleton.getInstance().getConexionServidor().validarAtributos(jTextFieldTabla.getText(),jTextFieldExpr.getText()) || "*".equals(jTextFieldExpr.getText())){    
                        try{
                        String nombreTabla;
                        if(Singleton.getInstance().getConexionServidor().esTablaTemporalP(jTextFieldTabla.getText())){
                            nombreTabla = "#"+jTextFieldTabla.getText();
                        }else{
                            nombreTabla = jTextFieldTabla.getText();
                        }
                        Singleton.getInstance().getConexionServidor().realizarInstruccionSql(1,"SELECT "+jTextFieldExpr.getText()+" INTO  #"+jTextFieldResult.getText()+" FROM "+nombreTabla);
                        Singleton.getInstance().getConexionServidor().realizarInstruccionSql(0,"SELECT * FROM #"+jTextFieldResult.getText());
                        Singleton.getInstance().getConexionServidor().setRs(null);

                        String consulta = "SELECT * FROM #"+jTextFieldResult.getText();
                        Singleton.getInstance().getConexionServidor().realizarInstruccionSql(0, consulta);
                        Tabla nuevaTabla = new Tabla(jTextFieldResult.getText(),true,Singleton.getInstance().getConexionServidor().convertirVector2ArrayList(Singleton.getInstance().getConexionServidor().atributosCosulta()));
                        Singleton.getInstance().getConexionServidor().agregarNombreTabla(nuevaTabla);

                        //Funcion que hace la llamada para ver en la interfaz
                        Singleton.getInstance().getAdministrador().tablaProyeccion(this);
                        String consult = "SELECT "+jTextFieldExpr.getText()+" FROM "+nombreTabla;
                        String algebra = "Π "+jTextFieldExpr.getText()+" ("+jTextFieldTabla.getText()+")";
                        this.jTextAreaSql.setText(consult);
                        this.jTextAreaAlg.setText(algebra);

                        }catch(SQLException ex){
                            JOptionPane.showMessageDialog(this, "Ocurrio algun error inesperado durante"
                                        +" la ejecución", "Error inesperado", JOptionPane.ERROR_MESSAGE);
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Algun atributo seleccionado es incorrecto"
                                        , "Atributo incorrecto", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    String tabla = jTextFieldResult.getText();
                    JOptionPane.showMessageDialog(this, "Error el nombre para el resultado de la tabla: "
                                +tabla+" ya existe", "Existencia de la tabla resultado", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                String tabla = jTextFieldTabla.getText();
                JOptionPane.showMessageDialog(this, "Error la tabla: "
                                +tabla+" no existe.", "No existe tabla", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            if(Singleton.getInstance().getConexionServidor().existeTablaP(jTextFieldTabla.getText())){
                if(Singleton.getInstance().getConexionServidor().validarAtributos(jTextFieldTabla.getText(),jTextFieldExpr.getText()) || "*".equals(jTextFieldExpr.getText())){
                    try {
                        String nombreTabla;
                        if(Singleton.getInstance().getConexionServidor().esTablaTemporalP(jTextFieldTabla.getText())){
                            nombreTabla = "#"+jTextFieldTabla.getText();
                        }else{
                            nombreTabla = jTextFieldTabla.getText();
                        }
                        String consult = "SELECT "+jTextFieldExpr.getText()+" FROM "+nombreTabla;
                        String algebra = "Π "+jTextFieldExpr.getText()+" ("+jTextFieldTabla.getText()+")";
                        Singleton.getInstance().getConexionServidor().realizarInstruccionSql(0,consult);
                        Singleton.getInstance().getAdministrador().tablaProyeccion(this);
                        this.jTextAreaSql.setText(consult);
                        this.jTextAreaAlg.setText(algebra);

                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, "Ocurrio algun error inesperado durante"
                                    +" la ejecución", "Error inesperado", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Algun atributo seleccionado es incorrecto"
                                        , "Atributo incorrecto", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                String tabla = jTextFieldTabla.getText();
                JOptionPane.showMessageDialog(this, "Error la tabla: "
                                +tabla+" no existe.", "No existe tabla", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonEjecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaProyeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaProyeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaProyeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaProyeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaProyeccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEjec;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTableProyec;
    private javax.swing.JTextArea jTextAreaAlg;
    private javax.swing.JTextArea jTextAreaSql;
    private javax.swing.JTextField jTextFieldExpr;
    private javax.swing.JTextField jTextFieldResult;
    private javax.swing.JTextField jTextFieldTabla;
    // End of variables declaration//GEN-END:variables
}
