/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import proyectobd1.Singleton;
import proyectobd1.Tabla;

/**
 *
 * @author Gerald
 */
public class VentanaUnion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSeleccion
     */
    public VentanaUnion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ejecutarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txfNombreTabla2 = new javax.swing.JTextField();
        txfNombreTabla1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txAResultadoConsulta = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txfTablaResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ejecutarBtn.setText("Ejecutar");
        ejecutarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre Tabla 1: ");

        jLabel2.setText("Nombre Tabla 2: ");

        txAResultadoConsulta.setColumns(20);
        txAResultadoConsulta.setRows(5);
        jScrollPane1.setViewportView(txAResultadoConsulta);

        jLabel3.setText("Tabla  resultado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(21, 21, 21))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfNombreTabla2)
                                    .addComponent(txfNombreTabla1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfTablaResultado))))
                        .addGap(149, 149, 149)
                        .addComponent(ejecutarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(ejecutarBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfNombreTabla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfNombreTabla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfTablaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ejecutarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarBtnActionPerformed
        // TODO add your handling code here:
       if(!txfTablaResultado.getText().isEmpty()){
           if(Singleton.getInstance().getConexionServidor().existeTablaP(txfNombreTabla1.getText()) && Singleton.getInstance().getConexionServidor().existeTablaP(txfNombreTabla2.getText())){
               if(Singleton.getInstance().getConexionServidor().atributosIgualesP(Singleton.getInstance().getConexionServidor().obtenerAtributos(txfNombreTabla1.getText()), Singleton.getInstance().getConexionServidor().obtenerAtributos(txfNombreTabla2.getText()))){
                    String nombreTabla1;
                    String nombreTabla2;
                    if(Singleton.getInstance().getConexionServidor().esTablaTemporalP(txfNombreTabla1.getText())){
                        nombreTabla1 = "#"+txfNombreTabla1.getText();
                    }else{
                        nombreTabla1 = txfNombreTabla1.getText();
                    }
                    if(Singleton.getInstance().getConexionServidor().esTablaTemporalP(txfNombreTabla2.getText())){
                        nombreTabla2 = "#"+txfNombreTabla2.getText();
                    }else{
                        nombreTabla2 = txfNombreTabla2.getText();
                    }
                    
                   try {
                        Singleton.getInstance().getConexionServidor().realizarInstruccionSql(1,"SELECT * INTO  #"+txfTablaResultado.getText()+" FROM "+nombreTabla1+" UNION SELECT * FROM "+nombreTabla2);
                        Singleton.getInstance().getConexionServidor().realizarInstruccionSql(0,"SELECT * FROM #"+txfTablaResultado.getText());
                        Singleton.getInstance().getConexionServidor().setRs(null);
                        String consulta = "SELECT * FROM #"+txfTablaResultado.getText();
                        Singleton.getInstance().getConexionServidor().realizarInstruccionSql(0, consulta);
                        Tabla nuevaTabla = new Tabla(txfTablaResultado.getText(),true,Singleton.getInstance().getConexionServidor().convertirVector2ArrayList(Singleton.getInstance().getConexionServidor().atributosCosulta()));
                        Singleton.getInstance().getConexionServidor().agregarNombreTabla(nuevaTabla);
                        //Funcion que hace la llamada para ver en la interfaz
                        //Singleton.getInstance().getAdministrador().tablaSeleccion(this);
                   } catch (SQLException ex) {
                       Logger.getLogger(VentanaUnion.class.getName()).log(Level.SEVERE, null, ex);
                    }    
                    
               }else{
                   System.out.println("Las tablas no tienen la misma aridad");
               }
           }else{
               System.out.println("Una de las tablas no existe");
           }  
       }else{
           if(Singleton.getInstance().getConexionServidor().existeTablaP(txfNombreTabla1.getText()) && Singleton.getInstance().getConexionServidor().existeTablaP(txfNombreTabla2.getText())){
               if(Singleton.getInstance().getConexionServidor().atributosIgualesP(Singleton.getInstance().getConexionServidor().obtenerAtributos(txfNombreTabla1.getText()), Singleton.getInstance().getConexionServidor().obtenerAtributos(txfNombreTabla2.getText()))){
                    String nombreTabla1;
                    String nombreTabla2;
                    if(Singleton.getInstance().getConexionServidor().esTablaTemporalP(txfNombreTabla1.getText())){
                        nombreTabla1 = "#"+txfNombreTabla1.getText();
                    }else{
                        nombreTabla1 = txfNombreTabla1.getText();
                    }
                    if(Singleton.getInstance().getConexionServidor().esTablaTemporalP(txfNombreTabla2.getText())){
                        nombreTabla2 = "#"+txfNombreTabla2.getText();
                    }else{
                        nombreTabla2 = txfNombreTabla2.getText();
                    }
                    
                   try {
                        Singleton.getInstance().getConexionServidor().realizarInstruccionSql(0,"SELECT * FROM "+nombreTabla1+" UNION SELECT * FROM "+nombreTabla2);
                        //Funcion que hace la llamada para ver en la interfaz
                        //Singleton.getInstance().getAdministrador().tablaSeleccion(this);
                   } catch (SQLException ex) {
                       Logger.getLogger(VentanaUnion.class.getName()).log(Level.SEVERE, null, ex);
                    }    
                    
               }else{
                   System.out.println("Las tablas no tienen la misma aridad");
               }
           }else{
               System.out.println("Una de las tablas no existe");
           }
       }
    }//GEN-LAST:event_ejecutarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUnion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUnion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUnion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUnion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUnion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ejecutarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txAResultadoConsulta;
    private javax.swing.JTextField txfNombreTabla1;
    private javax.swing.JTextField txfNombreTabla2;
    private javax.swing.JTextField txfTablaResultado;
    // End of variables declaration//GEN-END:variables
}
